pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // 华为 Maven 仓库
        maven { url 'https://developer.huawei.com/repo/' }
    }
}

rootProject.name = "proscan"
include ':app' 